FROM kshino/apex-clipper-base:m1

WORKDIR /tmp

# RUN wget -O /tmp/ffmpeg.zip https://www.osxexperts.net/ffmpeg6arm.zip
# RUN wget -O /tmp/ffmpeg.zip https://www.osxexperts.net/ffmpeg6intel.zip 
# RUN unzip /tmp/ffmpeg.zip -d /bin/

ADD ./model/ /root/model/
ADD ./apex-tracker.py /root/
ADD ./apex-create-movie-each.py /root/
ADD ./docker/bootstrap.sh /root/
ADD ./ocr/apex-ocr.py /root/
ADD ./ocr/apex-result.py /root/
ADD ./apex-kill-clip.sh /root/
ADD ./apex-ocr.sh /root/
ADD ./apex-ocr-exporter.sh /root/
ADD ./add_battle_result.sh /root/
# ADD ./ocr/jpn.traineddata /usr/share/tesseract-ocr/4.00/tessdata/
#ADD ./docker/ffmpeg /usr/local/bin/

# ENTRYPOINT ["/root/bootstrap.sh"]
ENV VERSION=<version>
