version: "3.9"  # optional since v1.27.0
services:
  apex_tracker:
    volumes:
      - <path-to-dir>:/root/src_movie/dir02
      - <path-to-dir>:/root/out
      - <path-to-dir>:/root/ocr
      - <path-to-dir>:/root/work
      - <path-to-dir>:/root/apex_kill_clip
    image: kshino/apex_tracker:master
    entrypoint: ["/root/bootstrap.sh","-m","all"]
  apex_tracker_mount:
    volumes:
      - video:/root/out
      - apex_GameRecs2020:/root/src_movie/dir01
      - apex_GameRecs2021:/root/src_movie/dir02
      - apex_ocr:/root/ocr
      - apex_ocr:/root/work
      - apex_killclip:/root/apex_kill_clip
    image: kshino/apex_tracker:latest
    entrypoint: ["/root/bootstrap.sh","-m","kill_clip"]
    deploy:
      mode: replicated
      replicas: 1
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu, utility]
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
volumes:
  video:
    driver_opts:
      type: cifs
      o: "user=<user>,pass=<PWD>,dom=WORKGROUP,vers=3.0,sec=ntlmv2,rw,hard,uid=1000,gid=1000"
      device: "\\\\192.168.11.11\\video\\apex"
  apex_ocr:
    driver_opts:
      type: cifs
      o: "user=nocknocknock,pass=kYF9FyFb8LLmarwJoi4A,dom=WORKGROUP,vers=3.0,sec=ntlmv2,rw,hard,uid=1000,gid=1000"
      device: "\\\\192.168.11.11\\usbshare2\\apex_ocr\\apex"
  apex_killclip:
    driver_opts:
      type: cifs
      o: "user=<user>,pass=<PWD>,dom=WORKGROUP,vers=3.0,sec=ntlmv2,rw,hard,uid=1000,gid=1000"
      device: "\\\\192.168.11.11\\usbshare2\\apex_killclip"
  apex_GameRecs2020:
    driver_opts:
      type: cifs
      o: "user=<user>,pass=<PWD>,dom=WORKGROUP,vers=3.0,sec=ntlmv2,rw,hard,uid=1000,gid=1000"
      device: "\\\\192.168.11.11\\usbshare1-2\\GameRecs2020"
  apex_GameRecs2021:
    driver_opts:
      type: cifs
      o: "user=<user>,pass=<PWD>,dom=WORKGROUP,vers=3.0,sec=ntlmv2,rw,hard,uid=1000,gid=1000"
      device: "\\\\192.168.11.11\\usbshare1-2\\GameRecs2021"

