name: build container

on:
  push:
    paths:
      - src/**
      - .github/workflows/build-push.yml

env:
  dh_user: 'kshino'
  image: 'apex-clipper'
  tag_basename: 'm1'
  context: 'src'
  dockerfile_arm64: 'src/docker/Dockerfile-arm64'
  dockerfile_amd64: 'src/docker/Dockerfile-amd64'

jobs:
  build-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push amd64
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{env.dh_user}}/${{env.image}}:${{env.tag_basename}},${{env.dh_user}}/${{env.image}}:${{env.tag_basename}}-${{github.sha}}
          platforms: linux/amd64
          context: ${{env.context}}
          file: ${{env.dockerfile_amd64}}
  build-arm64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push arm64
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{env.dh_user}}/${{env.image}}:${{env.tag_basename}},${{env.dh_user}}/${{env.image}}:${{env.tag_basename}}-${{github.sha}}
          platforms: linux/arm64
          context: ${{env.context}}
          file: ${{env.dockerfile_arm64}}
